[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short

# 配置base-url
base_url = http://localhost:8081

# 配置allure报告
allure_output_dir = allure-results
allure_clean = true

# 配置日志
log_cli = true
log_cli_level = INFO
log_file = logs/ruoyi_test.log
log_file_level = INFO